name: GitHub Actions for Responder
on: 
  push:
    # branches: 
    #   - main
jobs:
  # Explore-GitHub-Actions:
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #     - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "ğŸ This job's status is ${{ job.status }}."
  #     - name: dannys script
  #       run: sh ./script.sh
  Deploy-Responder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # install aws cli
      # - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #       unzip awscliv2.zip
      #       sudo ./aws/install
      # configure cli
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # install serverless globally
      - run: npm install serverless -g
      # configure serverless

      - run: npm install
      # - run: npm run deploy
      - run: printenv


  # on:
  # # Trigger the workflow on push or pull request,
  # # but only for the main branch
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # # Also trigger on page_build, as well as release created events
  # page_build:
  # release:
  #   types: # This configuration does not affect the page_build event above
  #     - created
